version: '3'

services:
  web:
    build: ./container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8003:8000"
    depends_on:
      - db
  db:
    platform: linux/amd64
    image: mysql:8.0
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: chat_demo
        MYSQL_HOST: db
        MYSQL_USER: sample
        MYSQL_PASSWORD: sample
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "23336:3306"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  my-mysql-data: